### ISSUE TITLE
Register Key Curl Command

### ISSUE THREAD

**Issue by lgbaeza** [WatsonAnalytics/oauth2-nodejs#1]
Inside the Readme file, whithin the instructions to Register the API Explorer keys:
_'https://example.com:5443"_ should be: _"https://example.com:5443"_ (changing simple quote to double quote ' -> ")
Thank you for sharing, this is very useful to accelerate WA API utilization

**Comment by MartinPetitclerc** [comment]
Fixed, thank you!
